spring.application.name=backend
# ===== Server =====
server.port=8082

# ===== PostgreSQL connection =====
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=appuser
spring.datasource.password=apppass
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
# 'update' = auto-create/update tables from @Entity classes (good for dev)
# Use 'validate' or 'none' in production and manage schema with migrations (Flyway/Liquibase).
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
